---
title: "sse"
author: "Sakana"
date: "11/3/2018"
output: html_document
---


### Load Libraries

```{r}
library(GenSA)
library(ggplot2)
library(GA)
library(knitr)
library(kableExtra)
```

#### SUM OF SQUARES OF ERROR

### USING GENETIC ALGORITHM
```{r}
x=c(5, 6, 25, 21, 25,  2,  36, 11,  28, 19)
y= c(12, 20,  8,  5,  6, 18,  35, 11,  44, 15)  
m<-data.frame(x=c(5, 6, 25, 21, 25,  2,  36, 11,  28, 19),y= c(12, 20,  8,  5,  6, 18,  35, 11,  44, 15))  
plot(m)
lm(m)
abline(lm(m))
obj <- function(a,b) {
  sum((y-(a+b*x))^2)
}
obj1 <- function(z) {
  -obj(z[1],z[2])
}
lower <- c(1,12)
upper<- c(10,30)
gam <- ga(type = "real-valued",fitness=obj1,lower=rep(0,2),upper=rep(1,2), popSize = 300,maxiter = 150)
 summary(gam)
```

#### USING SIMULATION ANNELING
```{r}
plot(m)
lm(m)
abline(lm(m))
obj <- function(a,b) {
  sum((y-(a+b*x))^2)
}
obj1 <- function(z) {
  obj(z[1],z[2])
}
lower <- c(1,12)
upper<- c(10,30)
Gensa <- GenSA(fn = obj1, lower = rep(0, 2), upper = rep(1, 2), control = list(smooth = FALSE, max.call = 150))
sol<-Gensa[c("value","par","counts")]
sol
```
#### Comparing Answers

```{r}
bo_b1_ga<-c(0.002061714,0.02005659)
bo_b1_gsa<-c(1.0000000, 0.7853394)
```

### Plotting Table

```{r}
data.frame(bo_b1_ga,bo_b1_gsa)
```

```{r}
Fitness_function_value_ga<-c(4357.87 )
Fitness_function_value_gsa<-c(1498.989)
data.frame(Fitness_function_value_ga,Fitness_function_value_gsa)
Itterations_ga<-c(150)
Itteratiojns_gsa<-c(150)
data.frame(Itterations_ga,Itteratiojns_gsa)
```
### GGPLOT 


```{r}
p <- ggplot(data = m,aes(x=x,y=y,))+ geom_point() +
  stat_smooth(formula = y~x, method = lm, se=F, aes(colour = "Regression") )+
  geom_abline(aes(slope = 0.9463667, intercept = 0.788123,color="GA"))+
  geom_abline(aes(slope=0.9999999, intercept=0.7853204,color="SA")) +
  ggtitle("PLOTTING OF GA,SA,REGRESSION") +
  scale_color_manual(NULL, values = c("GA" = "blue", "SA" = "red", "Regression" = "black"))
  
p
```
